### Healthcheck
GET {{url}}/auth/healthcheck

### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### Add admin role to user
POST {{url}}/auth/user/role/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}

### GET /candidates
GET {{url}}/candidates

### GET /candidates/{id}
GET {{url}}/candidates/1


### POST /candidates
POST {{url}}/candidates
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "name": "Eva Nielsen",
  "phone": "55555555",
  "education": "Javascript Developer",
  "skillIds": []
}


### PUT /candidates/{id}
PUT {{url}}/candidates/2
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "phone": "88888888",
  "education": "Bachelor i Datamatiker",
  "skillIds": [
    1,
    4
  ]
}


### DELETE /candidates/{id}3
DELETE {{url}}/candidates/3
Authorization: Bearer {{jwt_token}}


### PUT /candidates/{candidateId}/skills/{skillId} - link skill
PUT {{url}}/candidates/1/skills/2
Authorization: Bearer {{jwt_token}}

### DELETE /candidates/{candidateId}/skills/{skillId} – unlink igen
DELETE {{url}}/candidates/1/skills/2
Authorization: Bearer {{jwt_token}}